id: IDABD0D48
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T05:03:32+00:00'
last_modified: '2022-06-15T17:03:55.729905+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4449
  title: བཅོམ་ལྡན་འདས་དཔལ་དགྱེས་པ་རྡོ་རྗེའི་ཆོ་ག་ནག་པོ་འགྲོ་ཤེས་སུ་བཀོད་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9F4E:
      image_group_id: I1KG4537
      title: Volume 1 of bcom ldan 'das dpal dgyes pa rdo rje'i cho ga nag po 'gro
        shes su bkod pa
      total_pages: 636
      order: 1
      base_file: 9F4E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
